/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package JFSAP;

/**
 *
 * @author Morgan Higginbotham
 */
public class DownloadFileViaURLPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public DownloadFileViaURLPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        urllabel = new javax.swing.JLabel();
        urltextfield = new javax.swing.JTextField();
        downloadbutton = new javax.swing.JButton();
        yearlabel = new javax.swing.JLabel();
        quarterlabel = new javax.swing.JLabel();
        yeartextfield = new javax.swing.JTextField();
        quartertextfield = new javax.swing.JTextField();

        urllabel.setText("URL:");

        urltextfield.setText("https://www.sec.gov/Archives/edgar/full-index/ form.idx");
        urltextfield.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                urltextfieldActionPerformed(evt);
            }
        });

        downloadbutton.setText("Download");
        downloadbutton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                downloadbuttonActionPerformed(evt);
            }
        });

        yearlabel.setText("Year:");

        quarterlabel.setText("Quarter:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(downloadbutton)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(urllabel)
                            .addComponent(yearlabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(yeartextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(quarterlabel)
                                .addGap(18, 18, 18)
                                .addComponent(quartertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(urltextfield, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(urllabel)
                    .addComponent(urltextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yearlabel)
                    .addComponent(quarterlabel)
                    .addComponent(yeartextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quartertextfield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(downloadbutton)
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void urltextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urltextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_urltextfieldActionPerformed

    private void downloadbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downloadbuttonActionPerformed
        if (evt.getSource() == downloadbutton){
            IO.downloadFile(urltextfield.getText(),"Index\\" + yeartextfield.getText() + "\\Q" + quartertextfield.getText(), "companyform.idx");
            Storage.writeToIndexLog(Integer.parseInt(yeartextfield.getText()), Integer.parseInt(quartertextfield.getText()));
        }
    }//GEN-LAST:event_downloadbuttonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton downloadbutton;
    private javax.swing.JLabel quarterlabel;
    private javax.swing.JTextField quartertextfield;
    private javax.swing.JLabel urllabel;
    private javax.swing.JTextField urltextfield;
    private javax.swing.JLabel yearlabel;
    private javax.swing.JTextField yeartextfield;
    // End of variables declaration//GEN-END:variables
}
